---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

commonLabels:
  component: grafana-instance

resources:
  - ../base
  - session-secret.yaml
  - injected-certs-cm.yaml
  - grafana-proxy-rbac.yaml
  - grafana.yaml
