apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources section lists all the resources to include in the kustomization.
resources:
  - manifests/rendered.yaml
  - manifests/update-storage-config-secret.yaml
  # - manifests/job-to-patch-notebook-cr.yaml

# ConfigMapGenerator to include configuration files.
#configMapGenerator:
#  - name: dsc-team-onboard-config
#    files:
#      - helm-charts/dsc-team-onboard/values.yaml

# SecretGenerator to manage secrets, such as credentials.
#secretGenerator:
#  - name: dsc-team-onboard-secrets
#    files:
#      - path/to/your/secret/file

# Patches can be strategic, json 6902 or with files.
#patchesStrategicMerge:
#  - patch1.yaml
#  - patch2.yaml

# Images allows you to patch image names and tags.
#images:
#  - name: current-image-name
#    newName: new-image-name
#    newTag: new-image-tag


#Wave 0: Project creation.
#Wave 1: RBAC setup.
#Wave 2: Storage configuration.
#Wave 3: Data science pipelines setup.
#Wave 4: Notebook deployment.
