kind: ConfigMap
apiVersion: v1
metadata:
  name: notebook-controller-culler-config
  annotations:
    internal.config.kubernetes.io/previousKinds: ConfigMap
    internal.config.kubernetes.io/previousNames: notebook-controller-config
    internal.config.kubernetes.io/previousNamespaces: notebook-controller-system
    argocd.argoproj.io/sync-wave: '6'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/requester: argocd
  namespace: redhat-ods-applications
  labels:
    app: notebook-controller
    app.kubernetes.io/part-of: workbenches
    app.opendatahub.io/workbenches: 'true'
    component.opendatahub.io/name: kf-notebook-controller
    kustomize.component: notebook-controller
    opendatahub.io/component: 'true'
data:
  CULL_IDLE_TIME: '240'
  ENABLE_CULLING: 'true'
  IDLENESS_CHECK_PERIOD: '1'
