project:
  autoCreate: true
  name: credit-scoring
  user: risk-user
  notebook:
    type: pytorch
    name: credit-scoring-notebook
    description: to-predict-the-credit-score
    displayName: risk-model-for-credit-scoring
    appLabel: credit-scoring
    image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/pytorch:2024.2
    oauthInject: true
    lastImageSelection: tensorflow:2024.2
    lastSizeSelection: Medium
    notebookSize: Small
    gpu: 'No'
    mig: 'No'
    storageSizeLimit: 20Gi
    pvcSize: 20Gi
    cpuRequest: '1'
    cpuLimit: '2'
    memoryRequest: 8Gi
    memoryLimit: 16Gi
dspVersion: v2
apiServer:
  deploy: true
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 1Gi
  cABundle:
    configMapKey: ca.crt
    configMapName: kube-root-ca.crt
  customServerConfigMap:
    name: configmapname
    key: keyname
workflowController:
  deploy: true
  customConfig: custom-workflow-controller-configmap
persistenceAgent:
  deploy: true
  numWorkers: 2 #number of workers for sync job
  resources:
    requests:
      cpu: 120m
      memory: 500Mi
    limits:
      cpu: 250m
      memory: 1Gi
scheduledWorkflow:
  deploy: true
  cronScheduleTimezone: UTC
  resources:
    requests:
      cpu: 120m
      memory: 100Mi
    limits:
      cpu: 250m
      memory: 250Mi
mlpipelineUI:
  deploy: true
  image: quay.io/opendatahub/odh-ml-pipelines-frontend-container:beta-ui
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  configMap: ds-pipeline-ui-configmap
mlmd:
  deploy: true
  envoy:
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
  grpc:
    port: "8080"
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
database:
  mariaDB:
    deploy: true
    pipelineDBName: mlpipeline
    pvcSize: 10Gi
    username: mlpipeline
  customExtraParams: '{"tls":"false"}'
  disableHealthCheck: false
objectStorage:
  disableHealthCheck: false
  externalStorage:
    #host: os.apps.datascience.sndbox.intertech.com.tr
    host: 'minio-s3-minio.apps.cluster-slnkp.slnkp.sandbox321.opentlc.com'
    port: ''
    bucket: credit-scoring
    secure: true
    scheme: https
    basePath: pipeline-metadata
    s3CredentialsSecret:
      secretName: ds-pipeline-extobjstor-creds
      accessKey: AWS_ACCESS_KEY_ID
      secretKey: AWS_SECRET_ACCESS_KEY
  