
---
apiVersion: batch/v1
kind: Job
metadata:
  name: updating-storage-config-secret
  namespace: risk-credit-scoring
  annotations:
    argocd.argoproj.io/sync-wave: "86"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccount: credit-scoring-sa
      serviceAccountName: credit-scoring-sa
      containers:
      - name: updating-storage-config-secret
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args:
        - -ec
        - |-
          oc label secret/storage-config opendatahub.io/managed=false --overwrite

          export data_key_name=ds-pipeline-extobjstor-creds
          export new_data=$(oc get secret storage-config -o jsonpath="{.data.${data_key_name}}"|base64 -d| jq '. + {"verify_ssl": "false"}'| base64 -w0)

          oc get secret storage-config -o yaml |sed  "s/${data_key_name}: .*/${data_key_name}: $new_data/" |oc replace -f -
      restartPolicy: Never