---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

commonLabels:
  component: minio

resources:
- namespace.yaml
- pvc.yaml
- serviceaccount.yaml
- create-root-user-job.yaml
- deployment.yaml
- service.yaml
- route.yaml
