kind: ConfigMap
apiVersion: v1
metadata:
  name: custom-mig-parted-config
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
data:
  config.yaml: |
    version: v1
    mig-configs:
      custom-gpu:
        # A100-40GB, A800-40GB
        - device-filter: ["0x20B010DE", "0x20B110DE"]
          devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 2
            "2g.10gb": 1
            "3g.20gb": 1