---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvidia-gpu-operator

commonLabels:
  component: nvidia-gpu

resources:
- namespace.yaml
- clusterpolicy.yaml
- subscription.yaml
- operatorgroup.yaml
- ../../installplan-approver-job/base
- custom-mig-parted-config.yaml
- device-plugin-config.yaml

patches:
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env"
      value:
      - name: NAMESPACE
        value: "nvidia-gpu-operator"
  target:
    kind: Job
    name: installplan-approver